name: BungeeWaiter
version: "1.0"
main: xyz.acrylicstyle.bw.BungeeWaiter
commands:
  notification:
    permission: "bungeewaiter.notification"
  versions:
    permission: "bungeewaiter.versions"
  salert:
    permission: "bungeewaiter.salert"